#! /bin/sh
# Synergy Client
# Linux kernel module init script

#
# Copyright (C) 2014-2019 TAIN, Inc.
#
# This file is part of Synergy Client Open Source Edition (OSE), as
# available from http://www.virtualbox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualBox OSE distribution. VirtualBox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

# chkconfig: 35 30 70
# description: VirtualBox Linux kernel module
#
### BEGIN INIT INFO
# Provides:       virtualbox
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: VirtualBox Linux kernel module
### END INIT INFO

start()
{
	PID=`ps -ef | grep synergyc | grep -v grep | awk '{print $2}'`
	if [ "$PID" = "" ];
	then
		echo "Starting synergyc modules..."
		/usr/bin/synergyc 192.168.1.20
	else
		echo "Already started synergyc modules..."
	fi
}

stop()
{
	PID=`ps -ef | grep synergyc | grep -v grep | awk '{print $2}'`
	if [ "$PID" = "" ];
	then
		echo "Already stopped synergyc modules..."
	else
		echo "Stopping synergyc modules..."
		kill -9 $PID
	fi
}

status()
{
	PID=`ps -ef | grep synergyc | grep -v grep | awk '{print $2}'`
	if [ "$PID" = "" ];
	then
		echo "Not started synergyc modules..."
	else
		echo "Already started synergyc modules...pid = $PID"
	fi
}

# enter the following variables in /etc/default/virtualbox:
#   SHUTDOWN_USERS="foo bar"  
#     check for running VMs of user foo and user bar
#   SHUTDOWN=poweroff
#   SHUTDOWN=acpibutton
#   SHUTDOWN=savestate
#     select one of these shutdown methods for running VMs

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop && start
	;;
status)
	status
	;;
*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac


